//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.EntityController
{
    [Serializable]
    public class SpawnEntityMsg : Message
    {
        public const string k_RosMessageName = "entity_controller_msgs/SpawnEntity";
        public override string RosMessageName => k_RosMessageName;

        public string asset_key;
        public string unique_id;
        public Geometry.PoseMsg pose;

        public SpawnEntityMsg()
        {
            this.asset_key = "";
            this.unique_id = "";
            this.pose = new Geometry.PoseMsg();
        }

        public SpawnEntityMsg(string asset_key, string unique_id, Geometry.PoseMsg pose)
        {
            this.asset_key = asset_key;
            this.unique_id = unique_id;
            this.pose = pose;
        }

        public static SpawnEntityMsg Deserialize(MessageDeserializer deserializer) => new SpawnEntityMsg(deserializer);

        private SpawnEntityMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.asset_key);
            deserializer.Read(out this.unique_id);
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.asset_key);
            serializer.Write(this.unique_id);
            serializer.Write(this.pose);
        }

        public override string ToString()
        {
            return "SpawnEntityMsg: " +
            "\nasset_key: " + asset_key.ToString() +
            "\nunique_id: " + unique_id.ToString() +
            "\npose: " + pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
