//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.EntityController
{
    [Serializable]
    public class UpdatePoseEntityMsg : Message
    {
        public const string k_RosMessageName = "entity_controller_msgs/UpdatePoseEntity";
        public override string RosMessageName => k_RosMessageName;

        public string unique_id;
        public Geometry.PoseMsg pose;

        public UpdatePoseEntityMsg()
        {
            this.unique_id = "";
            this.pose = new Geometry.PoseMsg();
        }

        public UpdatePoseEntityMsg(string unique_id, Geometry.PoseMsg pose)
        {
            this.unique_id = unique_id;
            this.pose = pose;
        }

        public static UpdatePoseEntityMsg Deserialize(MessageDeserializer deserializer) => new UpdatePoseEntityMsg(deserializer);

        private UpdatePoseEntityMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.unique_id);
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.unique_id);
            serializer.Write(this.pose);
        }

        public override string ToString()
        {
            return "UpdatePoseEntityMsg: " +
            "\nunique_id: " + unique_id.ToString() +
            "\npose: " + pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
